### ISSUE TITLE
Tpay Improvements

### ISSUE THREAD

**Issue by arti0090** [CommerceWeavers/SyliusTpayPlugin#107]
- [x] fixes for card form
![Image](https://github.com/user-attachments/assets/9b2fb806-bc4b-4132-a773-9b2d77f53cc4)

- [x] add links to privacy and conditions
regulamin Tpay (wersja PL):
https://tpay.com/user/assets/files_for_download/regulamin.pdf
polityka prywatności (wersja PL):
https://tpay.com/user/assets/files_for_download/klauzula-informacyjna-platnik.pdf
regulamin Tpay (wersja EN):
https://tpay.com/user/assets/files_for_download/payment-terms-and-conditions.pdf
polityka prywatności (wersja EN):
https://tpay.com/user/assets/files_for_download/information-clause-payer.pdf

![Image](https://github.com/user-attachments/assets/01515859-005f-4ac7-a0ab-023b9ce61701)

- [x] send full data of user
![Image](https://github.com/user-attachments/assets/2953fdfb-7ce1-421d-8ecb-9838673b8abb)

- [x] gateway config translations
![Image](https://github.com/user-attachments/assets/44708b46-4a12-46fb-9b8a-b5bdc31c6422)

**Comment by jakubtobiasz** [comment]
Replaced by #118
