### ISSUE TITLE
Add possibility to declare payment with redirection in admin panel

### ISSUE THREAD

**Issue by lchrusciel** [CommerceWeavers/SyliusTpayPlugin#191]
We need to revive the content of https://github.com/CommerceWeavers/SyliusTpayPlugin/pull/42. Some payment providers require redirecting to a particular page. To do so, we need to add the channel ID to the payment request for pay. 

There should be a possibility to select:
* PayPo
* Raty Pekao
* Alior Raty
* Twisto

There may be a possibility to select anything from all returned channels

**Comment by jakubtobiasz** [comment]
Closing as replaced by #192, thanks 🙌🏼.
