### ISSUE TITLE
DX-770 Respect Tpay payment channel constraints when displaying available payment methods

### ISSUE THREAD

**Issue by jakubtobiasz** [CommerceWeavers/SyliusTpayPlugin#194]
## Description 📄

Currently, we display always all available Tpay channels when a customer chooses a Pay-By-Link payment method. However, some of them have some constraints, like the total amount should be between `200 PLN` and `2000 PLN`. We should read the constraints we are getting along the channel data and respect them when displaying channels to be chosen.

## Small wins 🏆

- [ ] Channels not available for a given order total are not displayed to a customer
- [ ] Payment methods (requires #192) that do not meet the constraints are not displayed

## Tips 💡

Constraints are returned from the API, so we just need to read it and apply at *some* point
- The second small win considers the #192 is already done; however, we can start this task before merging #192

**Comment by lchrusciel** [comment]
This covers also DX-811. We should take care of filtration of PBL with preselected channels as well
