### ISSUE TITLE
Direct transfer transactions (PBL) improvements

### ISSUE THREAD

**Issue by jakubtobiasz** [CommerceWeavers/SyliusTpayPlugin#66]
After delivering `Pay by Link` functionality, where we can choose a bank we want to be redirected directly, we have some improvements to be done.

## Small wins 🏆
- [x] Caching is done via a decoration, not directly in the service [[ref]](https://github.com/CommerceWeavers/SyliusTpayPlugin/pull/42#discussion_r1784057380)
- [x] Creating a PBL transaction is unified and uses the same mechanisms as other types [[ref]](https://github.com/CommerceWeavers/SyliusTpayPlugin/pull/42#discussion_r1789215098)
- [x] New payment details data is added to our `PaymentDetails` model [[ref]](https://github.com/CommerceWeavers/SyliusTpayPlugin/pull/42#discussion_r1789224243)
- [x] PBL payment can be done via API [[ref]](https://github.com/CommerceWeavers/SyliusTpayPlugin/pull/42#issuecomment-2394174638)

**Comment by arti0090** [comment]
@jakubtobiasz the caching I have done in last commit of "parent PR" - here it is https://github.com/CommerceWeavers/SyliusTpayPlugin/pull/42/commits/18aaa5b1287ac1aec401db284704fa95f7ea7090

I think it should solve the first checkbox but better if you would confirm it :)

**Comment by jakubtobiasz** [comment]
Ah, right. Missed that.
